---
# Source: voting-reports/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: voting-reports
  labels:
    app.kubernetes.io/name: voting-reports
    helm.sh/chart: voting-reports-0.1.0
    app.kubernetes.io/instance: first-release-reports
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: voting-reports
    app.kubernetes.io/instance: first-release-reports

---
# Source: voting-reports/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: voting-reports
  labels:
    app.kubernetes.io/name: voting-reports
    helm.sh/chart: voting-reports-0.1.0
    app.kubernetes.io/instance: first-release-reports
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: voting-reports
      app.kubernetes.io/instance: first-release-reports
  template:
    metadata:
      labels:
        app.kubernetes.io/name: voting-reports
        app.kubernetes.io/instance: first-release-reports
    spec:
      containers:
        - name: voting-reports
          image: "enabledocker/voting_reports:1.0"
          imagePullPolicy: Always
          env:
          - name: DATABASE_HOST
            value: 'voting-requirements-database'
          - name: DATABASE_PORT
            value: '27017'
          - name: DATABASE_NAME
            value: 'voting'
          - name: REPORTER_SERVICE
            value: 'voting-reports'
          ports:
          - containerPort: 3000
          name: wordpress
      imagePullSecrets:
        - name: master-voting-reports
