---
# Source: voting-votes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: voting-votes
  labels:
    app.kubernetes.io/name: voting-votes
    helm.sh/chart: voting-votes-0.1.0
    app.kubernetes.io/instance: first-release-votes
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: voting-votes
    app.kubernetes.io/instance: first-release-votes
---
# Source: voting-votes/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: voting-votes
  labels:
    app.kubernetes.io/name: voting-votes
    helm.sh/chart: voting-votes-0.1.0
    app.kubernetes.io/instance: first-release-votes
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: voting-votes
      app.kubernetes.io/instance: first-release-votes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: voting-votes
        app.kubernetes.io/instance: first-release-votes
    spec:
      containers:
        - name: voting-votes
          image: "enabledocker/voting_votes:1.0"
          imagePullPolicy: Always
          env:
          - name: DATABASE_HOST
            value: 'voting-requirements-database'
          - name: DATABASE_PORT
            value: '27017'
          - name: DATABASE_NAME
            value: 'voting'
          - name: QUEUE_HOST
            value: 'voting-requirements-queue'
          - name: QUEUE_PORT
            value: '6379'
          - name: REPORTS_SERVICE
            value: 'voting-reports'
          - name: REPORTS_PORT
            value: '3000'
          ports:
          - containerPort: 3000
      imagePullSecrets:
        - name: master-voting-votes
