---
# Source: voting-vote/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: voting-vote
  labels:
    app.kubernetes.io/name: voting-vote
    helm.sh/chart: voting-vote-0.1.0
    app.kubernetes.io/instance: first-release-vote
    app.kubernetes.io/managed-by: Tiller
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: voting-vote
    app.kubernetes.io/instance: first-release-vote
---
# Source: voting-vote/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: voting-vote
  labels:
    app.kubernetes.io/name: voting-vote
    helm.sh/chart: voting-vote-0.1.0
    app.kubernetes.io/instance: first-release-vote
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: voting-vote
      app.kubernetes.io/instance: first-release-vote
  template:
    metadata:
      labels:
        app.kubernetes.io/name: voting-vote
        app.kubernetes.io/instance: first-release-vote
    spec:
      containers:
        - name: voting-vote
          image: "enabledocker/voting_vote:1.0"
          imagePullPolicy: Always
          env:
          - name: DATABASE_HOST
            value: 'voting-requirements-database'
          - name: DATABASE_PORT
            value: '27017'
          - name: DATABASE_NAME
            value: 'voting'
          - name: QUEUE_HOST
            value: 'voting-requirements-queue'
          - name: QUEUE_PORT
            value: '6379'
          - name: REPORTS_SERVICE
            value: 'voting-reports'
          - name: REPORTS_PORT
            value: '3000'
          - name: VOTING_SERVICE
            value: 'voting-votes'
          - name: VOTING_PORT
            value: '3000'
          - name: VOTE_SERVICE
            value: 'voting-vote'
          - name: VOTE_PORT
            value: '3000'
          ports:
          - containerPort: 3000
      imagePullSecrets:
        - name: master-voting-vote
---
# Source: voting-vote/templates/cert.yaml

---
# Source: voting-vote/templates/ing.yaml

